plugins {
    id 'java-library'
    id "me.champeau.jmh" version "0.7.3"
    id "io.morethan.jmhreport" version "0.9.6"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "com.leakyabstractions:result:1.0.2.0"
}

apply from: project.file('benchmark.gradle')
apply from: project.file('test.gradle')
