
# Continuous Integration
name: Build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest

    steps:

    # ================================
    # SHALLOW CLONE
    # ================================
    - name: Shallow clone
      uses: actions/checkout@v3

    # ================================
    # SET UP JDK
    # ================================
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-package: jdk
        java-version: 21

    # ================================
    # SETUP GRADLE
    # ================================
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

    # ================================
    # CHECK
    # ================================
    - name: Check
      uses: gradle/gradle-build-action@v2
      with:
        arguments: check --info --scan

    # ================================
    # BENCHMARK
    # ================================
    - name: Benchmark
      uses: gradle/gradle-build-action@v2
      with:
        arguments: jmh --info --scan

    # ================================
    # UPLOAD RESULTS
    # ================================
    - name: Upload Results
      uses: actions/upload-artifact@v3
      with:
        name: results.json
        path: ./benchmark/build/reports/jmh/results.json

    # ================================
    # MAKE BADGE
    # ================================
    - name: Make Badge
      shell: bash
      run: |
        SCENARIO="com.leakyabstractions.result.benchmark.SimpleFailureScenario"
        SCORE_RESULTS=`jq ".[] | select(.benchmark == \"$SCENARIO.results\").primaryMetric.score" ./benchmark/build/reports/jmh/results.json`
        SCORE_EXCEPTIONS=`jq ".[] | select(.benchmark == \"$SCENARIO.exceptions\").primaryMetric.score" ./benchmark/build/reports/jmh/results.json`
        TIMES_FASTER=`printf "%.0f\n" $(jq -n "$SCORE_RESULTS / $SCORE_EXCEPTIONS")`
        LOGO_CONTENTS=`cat ./benchmark/build/reports/jmh/badge-logo.svg`
        echo "According to the benchmark, returning a failed result is $TIMES_FASTER times faster than throwing an exception"
        jq -n ".schemaVersion |= 1                                   |
               .style         |= \"for-the-badge\"                   |
               .labelColor    |= \"eee\"                             |
               .color         |= \"purple\"                          |
               .label         |= \"$TIMES_FASTER×\"                  |
               .message       |= \"faster than throwing exceptions\" |
               .logoSvg       |= \"$LOGO_CONTENTS\"                  " > ./benchmark/build/reports/jmh/badge.json

    # ================================
    # DEPLOY GITHUB PAGES
    # ================================
    - name: Deploy GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./benchmark/build/reports/jmh
